class SecretEntryBuffer:
    def __init__(self, capacity: int = 512) -> None: ...
    @property
    def length(self) -> int: ...
    def append(self, character: str) -> None: ...
    def backspace(self) -> None: ...
    def take(self) -> str: ...
    def clear(self) -> None: ...
