"""Agent-facing contract for durable Data metadata."""

from typing import Protocol

from corthena.contracts.data import CatalogRevisionDTO, ProgressDTO, ScheduleDTO


class DataRepositoryProtocol(Protocol):
    def close(self) -> None: ...

    def current_revision(self, dataset_id: str) -> CatalogRevisionDTO | None: ...

    def catalog(self) -> tuple[CatalogRevisionDTO, ...]: ...

    def publish(self, revision: CatalogRevisionDTO, expected_revision: int) -> None: ...

    def put_progress(self, progress: ProgressDTO, command_id: str) -> None: ...

    def progress(self, operation_id: str) -> ProgressDTO | None: ...

    def progress_by_command(self, command_id: str) -> ProgressDTO | None: ...

    def claim_command(
        self,
        command_id: str,
        resource_kind: str,
        resource_id: str,
        request_fingerprint: str,
    ) -> bool: ...

    def recover_incomplete(self) -> tuple[str, ...]: ...

    def schedules(self) -> tuple[ScheduleDTO, ...]: ...

    def schedule(self, schedule_id: str) -> ScheduleDTO | None: ...

    def create_schedule(self, schedule: ScheduleDTO) -> ScheduleDTO: ...

    def update_schedule(self, schedule: ScheduleDTO, expected_revision: int) -> ScheduleDTO: ...

    def delete_schedule(self, schedule_id: str, expected_revision: int) -> None: ...

    def credential_test_status(self) -> tuple[str | None, bool | None, str | None]: ...

    def set_credential_test_status(self, tested_at: str, succeeded: bool, detail: str) -> None: ...

    def clear_credential_test_status(self) -> None: ...
